### ISSUE TITLE
There are no functions/arguments for some of the task properties

### ISSUE THREAD

**Issue by Jackenmen** [cirrus-modules/helpers#8]
Here's a (potentially incomplete) list:
- allow_failures
- auto_cancellation
- execution_lock
- matrix
- only_if
- required_pr_labels
- skip
- skip_notifications
- stateful
- timeout_in
- trigger_type

It is still possible to use these fields by passing manually constructed dicts through `instructions` list but from what I understand these are supposed to let you avoid dealing with constructing dicts.

**Comment by bartekpacia** [comment]
@fkorotkov Is there a YAML schema of the `.cirrus.yaml` format?
